import { useEffect, useState } from "react";
import { useBootstrap } from "../hooks/useBootstrap";import { useStandings } from "../hooks/useStandings";import { useUpdatePreferences } from "../hooks/useUpdatePreferences";
import { Spinner } from "../components/Spinner";import { GlassCard } from "../components/GlassCard";import { assetFor,imageFallback,placeholders } from "../assets/assets";import { useI18n } from "../i18n/I18nContext";import { useAppTheme } from "../theme/ThemeContext";import { teamColor } from "../theme/teamColors";
export function Personalization(){const boot=useBootstrap(),drivers=useStandings("drivers"),teams=useStandings("constructors"),mutation=useUpdatePreferences();const{t}=useI18n();const theme=useAppTheme();const [ids,setIds]=useState<string[]>([]),[team,setTeam]=useState<string|null>(null),[toast,setToast]=useState(false);
useEffect(()=>{if(boot.data){setIds([boot.data.profile.preferences.favoriteDriverId,boot.data.profile.preferences.favoriteDriver2Id].filter(Boolean) as string[]);setTeam(boot.data.profile.preferences.favoriteConstructorId)}},[boot.data]);
useEffect(()=>()=>theme.restoreTheme(),[]);
if(boot.isLoading||drivers.isLoading||teams.isLoading)return <div className="rh-content"><Spinner/></div>;
const toggle=(id:string)=>setIds(v=>v.includes(id)?v.filter(x=>x!==id):v.length<2?[...v,id]:[v[1],id]);const chooseTeam=(id:string|null,color?:string)=>{setTeam(id);theme.previewTheme(color)};
const save=()=>mutation.mutate({favoriteDriverId:ids[0]??null,favoriteDriver2Id:ids[1]??null,favoriteConstructorId:team},{onSuccess:()=>{setToast(true);setTimeout(()=>setToast(false),1600)}});
return <div className="rh-content"><div className="pp-wordmark">Podium Pulse</div><h1 className="pp-page-title">{t("personalization")}</h1>{toast&&<div className="pp-toast">{t("saved")}</div>}<div className="rh-section-title">{t("currentSelection")}</div><GlassCard><div className="pp-muted">{ids.map(id=>drivers.data?.standings.find(s=>s.driver?.id===id)?.driver?.fullName).filter(Boolean).join(" · ")||t("selectDrivers")}</div><div style={{fontWeight:800,marginTop:8}}>{teams.data?.standings.find(s=>s.constructor?.id===team)?.constructor?.name||t("defaultTheme")}</div></GlassCard>
<div className="rh-section-title">1 · {t("selectDrivers")}</div><div className="pp-select-grid">{drivers.data?.standings.map(s=><GlassCard key={s.driver!.id} className="pp-choice" data-selected={ids.includes(s.driver!.id)} onClick={()=>toggle(s.driver!.id)} role="button"><strong>{s.driver!.fullName}</strong><span className="pp-muted">#{s.driver!.number??s.driver!.code}</span><img className="pp-choice__number-graphic" src={assetFor.number(s.driver!.id)} onError={e=>{e.currentTarget.style.display="none"}} alt=""/><img src={assetFor.driver(s.driver!.id)} onError={e=>imageFallback(e,placeholders.driverPlaceholder)} alt=""/></GlassCard>)}</div>
<div className="rh-section-title">2 · {t("selectTeam")}</div><div className="pp-select-grid"><GlassCard className="pp-choice" data-selected={!team} onClick={()=>chooseTeam(null)} role="button"><strong>{t("defaultTheme")}</strong><span className="pp-muted">{t("defaultThemeDesc")}</span></GlassCard>{teams.data?.standings.map(s=><GlassCard key={s.constructor!.id} className="pp-choice" data-selected={team===s.constructor!.id} onClick={()=>chooseTeam(s.constructor!.id,teamColor(s.constructor!.id,s.constructor!.color))} role="button"><strong>{s.constructor!.name}</strong><img src={assetFor.team(s.constructor!.id)} onError={e=>imageFallback(e,placeholders.teamPlaceholder)} alt=""/></GlassCard>)}</div><div className="pp-save-bar"><button className="rh-btn-primary" style={{width:"100%"}} disabled={mutation.isPending} onClick={save}>{t("save")}</button></div>{mutation.isError&&<p className="pp-muted">{t("dataUnavailable")}</p>}</div>}
